Update carbon-cache.erb

diff --git a/templates/etc/init.d/RedHat/carbon-cache.erb b/templates/etc/init.d/RedHat/carbon-cache.erb
--- a/templates/etc/init.d/RedHat/carbon-cache.erb
+++ b/templates/etc/init.d/RedHat/carbon-cache.erb
@@ -75,9 +75,21 @@ stop()
         ${PYTHON_CMD} ${GRAPHITE_DIR}/bin/carbon-${CARBON_DAEMON}.py --instance=${INSTANCE} stop;
         sleep 3
         while [ -f ${GRAPHITE_DIR}/storage/carbon-${CARBON_DAEMON}-${INSTANCE}.pid ]; do
-            echo "waiting another 5 secs for carbon-${CARBON_DAEMON}-${INSTANCE} to stop"
-            sleep 5
-            #TODO: add timer to prevend endless waiting
+            # break out of the loop if we have reached the retry limit
+            if [ ${CNT} -lt 1 ]; then
+                break
+            fi
+            CNT=$(expr ${CNT} - 1)
+            
+            # check to see if the pid in the file actually exists
+            pgrep -F ${GRAPHITE_DIR}/storage/carbon-${CARBON_DAEMON}-${INSTANCE}.pid > /dev/null 2>&1
+            if [ $? -eq 0 ]; then
+                echo "waiting another 5 secs for carbon-${CARBON_DAEMON}-${INSTANCE} to stop"
+                sleep 5
+            else
+                # pid does not exist, lets kill the pidfile!
+                rm -f ${GRAPHITE_DIR}/storage/carbon-${CARBON_DAEMON}-${INSTANCE}.pid
+            fi
         done
         rm -f /var/lock/subsys/carbon-${CARBON_DAEMON}-${INSTANCE}
         echo -n $"Stopping carbon-${CARBON_DAEMON}:${INSTANCE}..."
